<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error" kind="class" language="Python" prot="public">
    <compoundname>franka_tut_reasoning::errors::TargetUnknown_Error</compoundname>
    <basecompoundref refid="classfranka__tut__reasoning_1_1errors_1_1Error" prot="public" virt="non-virtual">franka_tut_reasoning.errors.Error</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1ac14a5e4835de67450016182e76c4ee0e" prot="public" static="no" mutable="no">
        <type></type>
        <definition>franka_tut_reasoning.errors.TargetUnknown_Error::value</definition>
        <argsstring></argsstring>
        <name>value</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" line="32" column="1" bodyfile="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" bodystart="32" bodyend="-1"/>
      </memberdef>
      <memberdef kind="variable" id="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1aa3132a50ff004562b83d2bdaea7586f5" prot="public" static="no" mutable="no">
        <type></type>
        <definition>franka_tut_reasoning.errors.TargetUnknown_Error::message</definition>
        <argsstring></argsstring>
        <name>message</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" line="33" column="1" bodyfile="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" bodystart="33" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1aa68de2099c5823297f25190bffe26f74" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def franka_tut_reasoning.errors.TargetUnknown_Error.__init__</definition>
        <argsstring>(self, symbol)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>symbol</type>
          <defname>symbol</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" line="31" column="1" bodyfile="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" bodystart="31" bodyend="34"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para><verbatim>Exception raised when one of the attribute of the request is not known </verbatim> </para>    </detaileddescription>
    <inheritancegraph>
      <node id="180">
        <label>Exception</label>
      </node>
      <node id="178">
        <label>franka_tut_reasoning.errors.TargetUnknown_Error</label>
        <link refid="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error"/>
        <childnode refid="179" relation="public-inheritance">
        </childnode>
      </node>
      <node id="179">
        <label>franka_tut_reasoning.errors.Error</label>
        <link refid="classfranka__tut__reasoning_1_1errors_1_1Error"/>
        <childnode refid="180" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="183">
        <label>Exception</label>
      </node>
      <node id="181">
        <label>franka_tut_reasoning.errors.TargetUnknown_Error</label>
        <link refid="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error"/>
        <childnode refid="182" relation="public-inheritance">
        </childnode>
      </node>
      <node id="182">
        <label>franka_tut_reasoning.errors.Error</label>
        <link refid="classfranka__tut__reasoning_1_1errors_1_1Error"/>
        <childnode refid="183" relation="public-inheritance">
        </childnode>
      </node>
    </collaborationgraph>
    <location file="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" line="28" column="1" bodyfile="franka_tut_reasoning/src/franka_tut_reasoning/errors.py" bodystart="28" bodyend="35"/>
    <listofallmembers>
      <member refid="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1aa68de2099c5823297f25190bffe26f74" prot="public" virt="non-virtual"><scope>franka_tut_reasoning::errors::TargetUnknown_Error</scope><name>__init__</name></member>
      <member refid="classfranka__tut__reasoning_1_1errors_1_1Error_1a7b2da2792da7abb0417f7d3128b8811f" prot="public" virt="non-virtual" ambiguityscope="franka_tut_reasoning::errors::Error."><scope>franka_tut_reasoning::errors::TargetUnknown_Error</scope><name>__init__</name></member>
      <member refid="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1aa3132a50ff004562b83d2bdaea7586f5" prot="public" virt="non-virtual"><scope>franka_tut_reasoning::errors::TargetUnknown_Error</scope><name>message</name></member>
      <member refid="classfranka__tut__reasoning_1_1errors_1_1TargetUnknown__Error_1ac14a5e4835de67450016182e76c4ee0e" prot="public" virt="non-virtual"><scope>franka_tut_reasoning::errors::TargetUnknown_Error</scope><name>value</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
